/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MeusNegociosRouteImport } from './routes/meus-negocios'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as BairrosRouteImport } from './routes/bairros'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NegocioIdRouteImport } from './routes/negocio.$id'
import { Route as EditarNegocioIdRouteImport } from './routes/editar-negocio.$id'
import { Route as BairroIdRouteImport } from './routes/bairro.$id'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminMunicipiosRouteImport } from './routes/admin.municipios'
import { Route as AdminDescobertaRouteImport } from './routes/admin.descoberta'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBairrosRouteImport } from './routes/admin.bairros'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminEmpresasIndexRouteImport } from './routes/admin.empresas.index'
import { Route as AdminEmpresasNovaRouteImport } from './routes/admin.empresas.nova'
import { Route as AdminEmpresasIdRouteImport } from './routes/admin.empresas.$id'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusNegociosRoute = MeusNegociosRouteImport.update({
  id: '/meus-negocios',
  path: '/meus-negocios',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const BairrosRoute = BairrosRouteImport.update({
  id: '/bairros',
  path: '/bairros',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioIdRoute = NegocioIdRouteImport.update({
  id: '/negocio/$id',
  path: '/negocio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarNegocioIdRoute = EditarNegocioIdRouteImport.update({
  id: '/editar-negocio/$id',
  path: '/editar-negocio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BairroIdRoute = BairroIdRouteImport.update({
  id: '/bairro/$id',
  path: '/bairro/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMunicipiosRoute = AdminMunicipiosRouteImport.update({
  id: '/admin/municipios',
  path: '/admin/municipios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDescobertaRoute = AdminDescobertaRouteImport.update({
  id: '/admin/descoberta',
  path: '/admin/descoberta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBairrosRoute = AdminBairrosRouteImport.update({
  id: '/admin/bairros',
  path: '/admin/bairros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/admin/avaliacoes',
  path: '/admin/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasIndexRoute = AdminEmpresasIndexRouteImport.update({
  id: '/admin/empresas/',
  path: '/admin/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasNovaRoute = AdminEmpresasNovaRouteImport.update({
  id: '/admin/empresas/nova',
  path: '/admin/empresas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasIdRoute = AdminEmpresasIdRouteImport.update({
  id: '/admin/empresas/$id',
  path: '/admin/empresas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof BairrosRoute
  '/buscar': typeof BuscarRoute
  '/cadastrar': typeof CadastrarRoute
  '/favoritos': typeof FavoritosRoute
  '/meus-negocios': typeof MeusNegociosRoute
  '/perfil': typeof PerfilRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/bairros': typeof AdminBairrosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/descoberta': typeof AdminDescobertaRoute
  '/admin/municipios': typeof AdminMunicipiosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/bairro/$id': typeof BairroIdRoute
  '/editar-negocio/$id': typeof EditarNegocioIdRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/empresas/$id': typeof AdminEmpresasIdRoute
  '/admin/empresas/nova': typeof AdminEmpresasNovaRoute
  '/admin/empresas/': typeof AdminEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof BairrosRoute
  '/buscar': typeof BuscarRoute
  '/cadastrar': typeof CadastrarRoute
  '/favoritos': typeof FavoritosRoute
  '/meus-negocios': typeof MeusNegociosRoute
  '/perfil': typeof PerfilRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/bairros': typeof AdminBairrosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/descoberta': typeof AdminDescobertaRoute
  '/admin/municipios': typeof AdminMunicipiosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/bairro/$id': typeof BairroIdRoute
  '/editar-negocio/$id': typeof EditarNegocioIdRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/empresas/$id': typeof AdminEmpresasIdRoute
  '/admin/empresas/nova': typeof AdminEmpresasNovaRoute
  '/admin/empresas': typeof AdminEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof BairrosRoute
  '/buscar': typeof BuscarRoute
  '/cadastrar': typeof CadastrarRoute
  '/favoritos': typeof FavoritosRoute
  '/meus-negocios': typeof MeusNegociosRoute
  '/perfil': typeof PerfilRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/bairros': typeof AdminBairrosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/descoberta': typeof AdminDescobertaRoute
  '/admin/municipios': typeof AdminMunicipiosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/bairro/$id': typeof BairroIdRoute
  '/editar-negocio/$id': typeof EditarNegocioIdRoute
  '/negocio/$id': typeof NegocioIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/empresas/$id': typeof AdminEmpresasIdRoute
  '/admin/empresas/nova': typeof AdminEmpresasNovaRoute
  '/admin/empresas/': typeof AdminEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bairros'
    | '/buscar'
    | '/cadastrar'
    | '/favoritos'
    | '/meus-negocios'
    | '/perfil'
    | '/admin/analytics'
    | '/admin/avaliacoes'
    | '/admin/bairros'
    | '/admin/categorias'
    | '/admin/descoberta'
    | '/admin/municipios'
    | '/admin/usuarios'
    | '/bairro/$id'
    | '/editar-negocio/$id'
    | '/negocio/$id'
    | '/admin/'
    | '/admin/empresas/$id'
    | '/admin/empresas/nova'
    | '/admin/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bairros'
    | '/buscar'
    | '/cadastrar'
    | '/favoritos'
    | '/meus-negocios'
    | '/perfil'
    | '/admin/analytics'
    | '/admin/avaliacoes'
    | '/admin/bairros'
    | '/admin/categorias'
    | '/admin/descoberta'
    | '/admin/municipios'
    | '/admin/usuarios'
    | '/bairro/$id'
    | '/editar-negocio/$id'
    | '/negocio/$id'
    | '/admin'
    | '/admin/empresas/$id'
    | '/admin/empresas/nova'
    | '/admin/empresas'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bairros'
    | '/buscar'
    | '/cadastrar'
    | '/favoritos'
    | '/meus-negocios'
    | '/perfil'
    | '/admin/analytics'
    | '/admin/avaliacoes'
    | '/admin/bairros'
    | '/admin/categorias'
    | '/admin/descoberta'
    | '/admin/municipios'
    | '/admin/usuarios'
    | '/bairro/$id'
    | '/editar-negocio/$id'
    | '/negocio/$id'
    | '/admin/'
    | '/admin/empresas/$id'
    | '/admin/empresas/nova'
    | '/admin/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BairrosRoute: typeof BairrosRoute
  BuscarRoute: typeof BuscarRoute
  CadastrarRoute: typeof CadastrarRoute
  FavoritosRoute: typeof FavoritosRoute
  MeusNegociosRoute: typeof MeusNegociosRoute
  PerfilRoute: typeof PerfilRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminBairrosRoute: typeof AdminBairrosRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminDescobertaRoute: typeof AdminDescobertaRoute
  AdminMunicipiosRoute: typeof AdminMunicipiosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  BairroIdRoute: typeof BairroIdRoute
  EditarNegocioIdRoute: typeof EditarNegocioIdRoute
  NegocioIdRoute: typeof NegocioIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmpresasIdRoute: typeof AdminEmpresasIdRoute
  AdminEmpresasNovaRoute: typeof AdminEmpresasNovaRoute
  AdminEmpresasIndexRoute: typeof AdminEmpresasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-negocios': {
      id: '/meus-negocios'
      path: '/meus-negocios'
      fullPath: '/meus-negocios'
      preLoaderRoute: typeof MeusNegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bairros': {
      id: '/bairros'
      path: '/bairros'
      fullPath: '/bairros'
      preLoaderRoute: typeof BairrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/$id': {
      id: '/negocio/$id'
      path: '/negocio/$id'
      fullPath: '/negocio/$id'
      preLoaderRoute: typeof NegocioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar-negocio/$id': {
      id: '/editar-negocio/$id'
      path: '/editar-negocio/$id'
      fullPath: '/editar-negocio/$id'
      preLoaderRoute: typeof EditarNegocioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bairro/$id': {
      id: '/bairro/$id'
      path: '/bairro/$id'
      fullPath: '/bairro/$id'
      preLoaderRoute: typeof BairroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/municipios': {
      id: '/admin/municipios'
      path: '/admin/municipios'
      fullPath: '/admin/municipios'
      preLoaderRoute: typeof AdminMunicipiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/descoberta': {
      id: '/admin/descoberta'
      path: '/admin/descoberta'
      fullPath: '/admin/descoberta'
      preLoaderRoute: typeof AdminDescobertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bairros': {
      id: '/admin/bairros'
      path: '/admin/bairros'
      fullPath: '/admin/bairros'
      preLoaderRoute: typeof AdminBairrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/admin/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas/': {
      id: '/admin/empresas/'
      path: '/admin/empresas'
      fullPath: '/admin/empresas/'
      preLoaderRoute: typeof AdminEmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas/nova': {
      id: '/admin/empresas/nova'
      path: '/admin/empresas/nova'
      fullPath: '/admin/empresas/nova'
      preLoaderRoute: typeof AdminEmpresasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas/$id': {
      id: '/admin/empresas/$id'
      path: '/admin/empresas/$id'
      fullPath: '/admin/empresas/$id'
      preLoaderRoute: typeof AdminEmpresasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BairrosRoute: BairrosRoute,
  BuscarRoute: BuscarRoute,
  CadastrarRoute: CadastrarRoute,
  FavoritosRoute: FavoritosRoute,
  MeusNegociosRoute: MeusNegociosRoute,
  PerfilRoute: PerfilRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminBairrosRoute: AdminBairrosRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminDescobertaRoute: AdminDescobertaRoute,
  AdminMunicipiosRoute: AdminMunicipiosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  BairroIdRoute: BairroIdRoute,
  EditarNegocioIdRoute: EditarNegocioIdRoute,
  NegocioIdRoute: NegocioIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmpresasIdRoute: AdminEmpresasIdRoute,
  AdminEmpresasNovaRoute: AdminEmpresasNovaRoute,
  AdminEmpresasIndexRoute: AdminEmpresasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
